### ISSUE TITLE
Error in running nn_decomposer.py

### ISSUE THREAD

**Issue by lucwan** [wenwei202/caffe#10]
I am getting the following errors after running python python/nn_decomposer.py

raceback (most recent call last):
 File "../python/nn_decomposer.py", line 194, in <module>
   net_msg.layer._values.insert(layer_idx,low_rank_layer)
AttributeError: 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute '_values'

Traceback (most recent call last):
 File "../python/nn_decomposer.py", line 194, in <module>
   net_msg.layer.insert(layer_idx,low_rank_layer)
AttributeError: 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'insert'

i tried protobuf version 2.3, 2.5 and 3.3
what could possibly be wrong at my end, please help me.

**Comment by wenwei202** [comment]
Too bad, one of my colleagues met this before, let me check and get you back!

**Comment by wenwei202** [comment]
@lucwan feedback: you may need to find if you have installed multiple versions of protobuf (e.g., one in Anaconda and one in system directory). Please make sure you have completely uninstalled all of them, and reinstall one. It worked for us. Let me know it helps or not.

**Comment by lucwan** [comment]
Thank you @wenwei202 
I changed to another PC with Ubuntu 14.04 from Centos 6.7 and it worked fine.

**Comment by vc-30** [comment]
Hi @wenwei202 ,

First of all thanks for your work. I'm also facing similar issue and not sure how to fix the multiple protobuf issue. I checked [https://github.com/protocolbuffers/protobuf/issues/4001](url) but, this doesn't seem to be applicable in my case. 
Please guide me how can I fix this.

**Comment by wenwei202** [comment]
Protobuf always sucks. A quick try is to remove *all* installations of protobuf and reinstall. Sometimes, you will be in trouble if you have multiple versions of protobuf installed.
