### ISSUE TITLE
Training with Force Regularization

### ISSUE THREAD

**Issue by lucwan** [wenwei202/caffe#11]
@wenwei202  I am trying to train my network (Resnet like architecture) with force regularization. But I could not find any documentation on how to enable force regularization during training using my network.
From examples I can understand that "force_mult: 1" can be added to Convolution layer "param" to enable it. Is it the correct way or are there any other steps required?

**Comment by wenwei202** [comment]
@lucwan Some [tutorials](https://github.com/wenwei202/caffe/blob/master/README.md#lower-rank-deep-neural-networks-iccv-2017-1) are updated. Hope it can help.

**Comment by wenwei202** [comment]
Close as tutorials are added!
