### ISSUE TITLE
用scnn训练完后，测试模型时如果不用sparseblas会影响结果吗？

### ISSUE THREAD

**Issue by wenston2006** [wenwei202/caffe#13]
我的目的是借用scnn来压缩模型参数，但是在某些环境下（如安卓系统）缺乏sparseblas库；此时只能采用常规的卷积操作；如果我不用sparseblas测试压缩后的模型，会不会影响测试精度？

**Comment by wenwei202** [comment]
sparseblas is the one that SSL was compared to, and higher speedup than sparseblas was shown. 
After learning structured sparsity, you just need to remove all-zero rows and columns, then use matrix-matrix multiplication in common BLAS to perform computation.
So no sparseblas library is needed.

**Comment by wenston2006** [comment]
谢谢，如果我来做模型压缩，需要将为零的参数去掉，怎样判定哪些参数为零呢？参数此时应该是以float型储存的吧；是否可以设一个阈值如1e-5，然后将绝对值小于该阈值的参数判定为零？

**Comment by wenwei202** [comment]
Yes, you could do that!
