### ISSUE TITLE
Improve efficiency for group lasso

### ISSUE THREAD

**Issue by hiyijian** [wenwei202/caffe#19]
Dear @wenwei202 ,
  I found training speed get much much slower with group lasso than without it. I believe you must had the same experience. I hacked your code and found [this line](https://github.com/wenwei202/caffe/blob/e0a58fd71adeb7de9e17611652f91f53ee1461c2/src/caffe/util/math_functions.cu#L551) should be responsible for this efficiency decline(about 30%). I replace this kind of dynamic inquery to device, which is proved to be time-comsuming, with simply macro CAFFE_CUDA_NUM_THREADS. The training speed is now comparable to previous no group lasso one.

Hope this helpful. Thank you

**Comment by wenwei202** [comment]
Thanks.
