### ISSUE TITLE
where  cifar10_full_train_test_kernel_shape.prototxt ?

### ISSUE THREAD

**Issue by MrLinNing** [wenwei202/caffe#26]
sorry, but I can't find cifar10_full_train_test_kernel_shape.prototxt and `./examples/cifar10/train_script.sh` in https://github.com/wenwei202/caffe/blob/scnn/examples/cifar10/readme.md

**Comment by wenwei202** [comment]
Please go to scnn branch, they should be [there](https://github.com/wenwei202/caffe/tree/scnn/examples/cifar10).
