### ISSUE TITLE
Special steps required for implementation?

### ISSUE THREAD

**Issue by michaelholm-ce** [wenwei202/caffe#9]
Do I need to alter my train_val.prototxt file to take advantage of sparsity, or will this version of caffe implement sparsity for me?

For comparison, I took a model I had previously trained using vanilla caffe and retrained it with this caffe library.  Training executed and the model learned successfully, but there was no speed-up observed during inference.  So, I'm wondering if I need to make any changes to my train prototxt file to take advantage of the sparsity operations, since I didn't see any special instructions in the project readme.

Thank you.

**Comment by wenwei202** [comment]
Hi Did you use the branch of [scnn](https://github.com/wenwei202/caffe/tree/scnn)? I guess we have tutorials on how to do training and testing with sparsity enabled.

**Comment by michaelholm-ce** [comment]
I was using the master branch (default), and therefore did not see the tutorials.  I'll use the scnn branch and try again.  Thanks.
